numbers = [5, 2, 1, 7, 4, 5]
numbers.append(20)
print(numbers)
numbers.insert(2,13)
print(numbers)
numbers.remove(1)
print(numbers)
numbers.pop()
print(numbers)
print(numbers.index(7))
print(50 in numbers)
print(numbers.count(5))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
numbers2 = numbers.copy()
numbers.append(10)
print(numbers2)
numbers.clear()
print(numbers)